name: Cypress Tests with Dependency and Artifact Caching

on: push
defaults:
  run:
    working-directory: ./signit-interface
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    container:
      image: cypress/browsers:latest
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Cypress Globally
        run: npm install -g cypress

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CI: false
        with:
          working-directory: ./signit-interface
          build: pnpm build
          start: pnpm start
          browser: chrome

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: ./signit-interface/cypress/screenshots
          retention-days: 30

      - name: Upload Cypress reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-reports
          path: ./signit-interface/cypress/reports
          retention-days: 30
